### ISSUE TITLE
XSEQ files

### ISSUE THREAD

**Issue by ObludaIE** [onepiecefreak3/XtractQuery#1]
Hello,
Thank you for this tool ! 
Would it possible to look into XSEQ (not XQ32) files from Inazuma Eleven GO Dark/Light, here are some examples :
![image](https://user-images.githubusercontent.com/65013432/83247743-44406200-a1a4-11ea-9891-3a1569e7d29a.png)

**Comment by ObludaIE** [comment]
[XSEQ.zip](https://github.com/onepiecefreak3/XtractQuery/files/4701053/XSEQ.zip)

**Comment by Rytheex** [comment]
Same! I would need it too for the same reason.

**Comment by onepiecefreak3** [comment]
I will close this issue, since extraction support was added and seemed to be the only thing requested for now.
