### ISSUE TITLE
Reference scripts feature help

### ISSUE THREAD

**Issue by LordEnma** [onepiecefreak3/XtractQuery#12]
I'm sorry if this is stupid, but what scripts is this tool referring to when it asks me to place them in the reference folder? I have all the files for the game, I just don't know which ones this tools considers to be "scripts".

**Comment by onepiecefreak3** [comment]
It refers to other .xq scripts. Function calls in .xq scripts reference functions from other .xq scripts via checksum. So, if you put the .xq scripts in the reference folder that might contain the function with that checksum, it can be resolved to human-readable output.
