### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: The parameter value 9 could not be parsed. error on some xq32 file

### ISSUE THREAD

**Issue by RealDarkCraft** [onepiecefreak3/XtractQuery#5]
I have an error when i try to extract the ShopMenu.xq of yo-kai watch 1 for Switch

![Capture d’écran 2023-04-05 011908](https://user-images.githubusercontent.com/71570182/229943430-713ac8ce-9ce7-4663-95ad-2a5229604649.png)

**Comment by GachaFan** [comment]
there is a sample file 
[ShopMenu.zip](https://github.com/onepiecefreak3/XtractQuery/files/11153928/ShopMenu.zip)

**Comment by GachaFan** [comment]
it seem to correctly extract with the the oldest version of XtractQuery but when I try to repack them, if don't work

**Comment by GachaFan** [comment]
there is also the same error for part of the other files but with different parameters values ​​error
[seq.zip](https://github.com/onepiecefreak3/XtractQuery/files/11171251/seq.zip)

**Comment by onepiecefreak3** [comment]
Resolved in release 3.0.0.
