### ISSUE TITLE
XQ32 from Yo-Kai Watch 2: Psychic Specters cannot be extracted 

### ISSUE THREAD

**Issue by DanionelP** [onepiecefreak3/XtractQuery#6]
Most of the xq from the game can be extracted, but for some reason this one can't.
This is the output:
![image](https://github.com/onepiecefreak3/XtractQuery/assets/122308508/5d323c69-0c72-4ca0-ba5b-73781f41d398)

And this is the file:
[ev98_0020.zip](https://github.com/onepiecefreak3/XtractQuery/files/12378716/ev98_0020.zip)
The strange thing is that it works with older versions (1.3 and lower). I've checked and it is not a xseq file.

**Comment by onepiecefreak3** [comment]
Resolved in release 3.0.0.
