### ISSUE TITLE
Being able to extract multiple XQ's at the same time

### ISSUE THREAD

**Issue by DanionelP** [onepiecefreak3/XtractQuery#7]
I know I've just opened an issue, but I had to do another because this is a completely different thing. 
When I need to know what a function does, I have to look in all the files it is called. And to do so I have to extract a lot of XQ files.
The problem is that you can only extract one XQ at the same time, and it's very tedious. It would be neat to be able able to extract all the XQ files inside a given folder, it would be much faster.

**Comment by onepiecefreak3** [comment]
Added in release 3.0.0.
