### ISSUE TITLE
Error building a xq32 from ykw2 ps

### ISSUE THREAD

**Issue by pqr29** [onepiecefreak3/XtractQuery#8]
![Captura de pantalla 2023-09-23 201541](https://github.com/onepiecefreak3/XtractQuery/assets/140266839/3197bc20-8d2f-4845-bb8b-780bb68d1999)

here is the file

[c01_trigger_0.01.zip](https://github.com/onepiecefreak3/XtractQuery/files/12707043/c01_trigger_0.01.zip)

pd: its from ykw1 but i cant edit the title

**Comment by onepiecefreak3** [comment]
Resolved in release 3.0.0.
